# Beyond Spotify: Harnessing the Human Element of Music Recommendations {#music-discovery}

#### Keywords {-}

music, discovery, Pandora, Spotify

## The Problems with Music Algorithms

Music recommendation algorithms have been popular for the better part of twenty years. [Pandora](https://www.pandora.com/) blazed the trail in the early 2000s and [Spotify](https://www.spotify.com/us/) and others are now trying to assume control of that realm. Despite increasingly complex algorithms trying to identify matches between music and consumers, though, the algorithms are based on identifying musical links between songs, ignoring non-musical factors. 
[Published research](https://skynetandebert.com/2015/04/22/music-was-better-back-then-when-do-we-stop-keeping-up-with-popular-music/) shows that people become set in their musical tastes as time passes and that most people are set in their musical ways by their early 30's. This makes logical sense, as competing life priorities take precedence over time. People seem to care less as time goes on and many forget how to find new music, much in the way that some find it difficult to make new friends after a certain age. The anecdotal interest is there, though: whenever I hear someone say, “I don’t know any new music anymore,” I ask questions to learn why. I will occasionally hear, “I know what I like,” but the much more common response is, “I would love to find new music, but I don’t know where to start.” 
There is vast, untapped potential in the sizable passive consumer market. Artists, music apps, and record labels are not capitalizing on this income, and that represents an opportunity. My approach will identify artist links that go beyond musical algorithms and deliver material reliably to the passive end user.

## Music Discovery: Unconventional Resources

How can we bridge this gap? The existing algorithms are powerful from a strictly musical standpoint, but there are some basic variables that are evidently not considered. If an algorithm has a base of thirty independent rock songs with female vocals, but three songs later, spits out AC/DC, something is wrong with the algorithm. 
How should we define “new” music? Our goal is to recommend artists and songs to consumers that existing algorithms would not. This means that the material is not necessarily new, but it should be new to them. This algorithm will filter for independent artists and labels to increase the likelihood of making novel recommendations.
I plan to attack this issue from multiple angles:
1.	Social Media Mentions:  Non-musical links between artists will be most evident on social media; we can find them by pulling data from Facebook, Twitter, Instagram, and more music-focused apps like Songkick. Artists do not need to be active on social media for this to work: they only need users to mention them. Two bands that are commonly mentioned by a single user have a clear link that goes beyond the sound of the songs. 
2.	Bandcamp Collections: Another key source of data will be fan pages on Bandcamp. Whenever a consumer purchases music from an artist, it becomes part of a public fan page collection. Mining those collections for common links between artists will produce another key source for our recommendations. 
3.	Discogs Collections: Discogs is the world’s preeminent assemblage of music discographies and represents what should be the second largest music marketplace after eBay (sales figures are not public). Users are able to document their music collections through tools on the site; Discogs contains thousands of public collection lists that would provide an additional important resource.
4.	eBay: Finally, I will monitor eBay stores to see where there are common links between artists in sellers’ inventories. This is an imperfect measure, as sellers do not restrict themselves to individual genres. However, a large enough sample size will correct for that effect and should still produce useful data.  
I will cross-reference the correlations found in the various data sources, and test the algorithm’s outputs against suggestions made by the established industry leaders. If I find a statistically significant quantity of novel results, I can implement the delivery solution: short, tailored playlists, emailed to users on a weekly basis.

## Delivering to the Passive Listener

If a service were to deliver hour-long playlists based on your tastes via email on a weekly basis, would they intrigue you? Would you listen to them? They would take the time of a podcast and be just as portable. The ability to capitalize on the entertainment dollar of the passive music listener will hinge upon eliminating any activity that would require effort. If I can introduce them to new music without making them work for it, I can dramatically improve the consumer experience, and can then convert that experience into profits.
Naturally, the algorithm does not represent a perfect solution. No single platform will produce perfect results, and there will be a significant amount of noise in the data. However, with large enough sample sizes, I can correct for this sufficiently.
The major limitation of this model is that it relies on a user base that is online and willing to use the tools at their disposal to listen to music. In its current form, it will not reach users who rely exclusively on listening to physical formats. Once the first model is established, I will look for ways to reach these users. 
Every few years, innovation drives new financial successes in the music industry. There are major players in the music industry, but none of them have fully capitalized on the potential of the passive listener. My model can speak to the passive fan and could be the next big music innovation.
